### ISSUE TITLE
model in the esp32

### ISSUE THREAD

**Issue by RangeOfGlitching** [Marc56K/ElectricityMeterCam#2]
hello
I try to train my customized model and put it in the esp32
My model architecture is same as yours, but the size can't fit in the esp32.
And than I try to change other architecture to reduce the size of model.
After reduce the size, it can flash into esp32, but I still get the error 
Could you help me?

```
i = tf.keras.layers.Input(shape=(28, 28, 1))
x = tf.keras.layers.Conv2D(filters=16, kernel_size=(3, 3), activation="relu")(i)
x = tf.keras.layers.MaxPooling2D(pool_size=(2, 2))(x)
x = tf.keras.layers.Dropout(0.5)(x)
x = tf.keras.layers.Conv2D(filters=32, kernel_size=(3, 3), activation="relu")(x)
x = tf.keras.layers.MaxPooling2D(pool_size=(2, 2))(x)
x = tf.keras.layers.Dropout(0.5)(x)
x = tf.keras.layers.Conv2D(filters=32, kernel_size=(3, 3), activation="relu")(x)
x = tf.keras.layers.Flatten()(x)
x = tf.keras.layers.Dense(64, activation="relu")(x)
x = tf.keras.layers.Dropout(0.5)(x)
x = tf.keras.layers.Dense(10, activation="softmax")(x)
model = tf.keras.Model(inputs=i, outputs=x)
model.compile(optimizer="rmsprop",
              loss="categorical_crossentropy",
              metrics=["accuracy"])
model.summary()

```

error i got

abort() was called at PC 0x400d6cee on core 1

Backtrace:0x400838d1:0x3ffb23700x4008ec89:0x3ffb2390 0x400948e5:0x3ffb23b0 0x400d6cee:0x3ffb2430 0x400e7933:0x3ffb2490 0x400e7ae5:0x3ffb2530 0x400e819b:0x3ffb25f0 0x400e66f7:0x3ffb2670 0x400d39d2:0x3ffb2690 0x400d560e:0x3ffb2700 0x400d571e:0x3ffb2760 0x400d5ad2:0x3ffb27f0 0x400efd91:0x3ffb2820

**Comment by Marc56K** [comment]
Moin [RangeOfGlitching](https://github.com/RangeOfGlitching),

I didn't test you model yet but here are some ideas on this:

1. Your model has 10 output classes instead of 11. Make sure that this value is also set when loading the model in the main.cpp: `OCR ocr(ocr_model_28x28_c10_tflite, 28, 28, 10)`
The 11th class was intended for garbage images that don't show any number at all.

2. After the conversion of the *.tflite file to a *.c file, make sure that the generate variable in this file is `const` otherwise this takes a lot of additional RAM on the ESP: `const unsigned char ocr_model_28x28_c10_tflite[] = {...`

3. If you consider using larger models in the future, there is also the possibility to use the additional 4MB PSRAM of the ESP32-CAM. To do so, you have to change the following line in the OCR.cpp
from: `_tensorMemoryPool = (uint8_t*)malloc(tensor_pool_size);`
to `_tensorMemoryPool = (uint8_t*)ps_malloc(tensor_pool_size);`
I never tried this, but it should work in theory.

Let me know if you couldn't solve your issue, than we can dig deeper into this.

Marc

**Comment by RangeOfGlitching** [comment]
Hello, apologies for the delay in getting back to you, but after some testing I found something interesting
1.  Enen My model architecture is same as you, but my tflite model size is bigger than yours. (tensorflow2.6)
2.  Instead of global declare ocr obj as you do, I use new to create ocr object and put it in the global pointer ocr variable. And it work well!(But why?)

Instead of
`OCR ocr(ocr_model_28x28_c11_tflite, 28, 28, 11);`
what I do is
```
OCR *ocr;
void setup() {
....    
ocr = new OCR(ocr_model_28x28_c11_tflite, 28, 28, 11);
}
```


Thanks your advice
`_tensorMemoryPool = (uint8_t*)ps_malloc(tensor_pool_size);`
It's help me a lots

**Comment by Marc56K** [comment]
Hey, well done :-)
1. I'm not sure which tensorflow version I used that day but as long it is compatible with the used tfmicro version it shouldn't be a probleme.
2. Maybe the initialization of the camera server needs temporary more RAM that is only available if the OCR instance is create after this. Or it has something todo with memory fragmentation, I don't know.

Marc
